wandb_version: 1

learning_rate:
  desc: null
  value: 0.003
architecture:
  desc: null
  value: mobilenetv3
dataset:
  desc: null
  value: Lego-Minifigures
epochs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1696610813.312936
    t:
      1:
      - 1
      - 41
      - 49
      - 50
      - 55
      - 63
      - 105
      2:
      - 1
      - 41
      - 49
      - 50
      - 55
      - 63
      - 105
      3:
      - 16
      - 23
      4: 3.10.13
      5: 0.15.12
      8:
      - 3
      - 5
      13: windows-amd64
