train_transforms:
  train_transforms:
    - name: torchvision.transforms.RandomResizedCrop
      size: [224, 224]
    - name: torchvision.transforms.RandomHorizontalFlip
    - name: torchvision.transforms.RandomRotation
      degrees: 30
    - name: torchvision.transforms.RandomAffine
      degrees: 0
      translate: [0.1, 0.1]
    - name: torchvision.transforms.RandomPerspective
      distortion_scale: 0.5
      p: 0.5
    - name: torchvision.transforms.ToTensor
    - name: torchvision.transforms.Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

val_test_transforms:
  - name: torchvision.transforms.Resize
    size: [256, 256]
  - name: torchvision.transforms.CenterCrop
    size: [224, 224]
  - name: torchvision.transforms.ToTensor
  - name: torchvision.transforms.Normalize
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]