#Source: DTU MLOps workflows Skafte Nicki
name: Check code formatting

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 15 * * *"  # run every day at 15:00 UTC

jobs:
  name: Check code formatting on all platforms
  build-on-ubuntu:
    name: "Code formatting check on Ubuntu"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: flake8
        run: |
          flake8 .  --max-line-length 100

  build-on-macos:
    name: "Code formatting check on macOS"
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: flake8
        run: |
          flake8 .  --max-line-length 100

  build-on-womdows:
    name: "Code formatting check on Windows"
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: flake8
        run: |
          flake8 .  --max-line-length 100
